### ISSUE TITLE
Create first draft for the website

### ISSUE THREAD

**Issue by rochaporto** [cloud-native-suisse-romande/website#1]

**Comment by rochaporto** [comment]
Needs decision on joining KCD or not, before publishing.

**Comment by rochaporto** [comment]
Should we start with a placeholder page to pass to sponsors?

**Comment by oleg-nenashev** [comment]
I pushed the temporary association site to this repo. Once the naming is set, we can deploy another one with the engine of choice

**Comment by oleg-nenashev** [comment]
Done. I will do the conference itself in https://github.com/cloud-native-suisse-romande/website/issues/3
